package rules;

import com.example.springboot.model.CarBuyingRequest
import java.util.Date
import java.util.ArrayList;
import org.apache.commons.lang3.time.DateUtils;


/*

rule "Set AI Decision if godine < 100000"
when
    $request : CarBuyingRequest( age < 100000 )
then
    $request.setAiDecision(1);
    System.out.println("AI Decision set to 1 for request with godine < 100000");
end*/
// Define the main query for matching
// Define the main query for matching
query queryMatch(CarBuyingRequest $request)
    checkAge($request;)
    checkMonthlyIncome($request;)
end

// Define the query to check the age requirement
query checkAge(CarBuyingRequest $request)
    $r : CarBuyingRequest(this == $request, age < 65)
end

// Define the query to check the monthly income requirement
query checkMonthlyIncome(CarBuyingRequest $request)
    $r : CarBuyingRequest(this == $request, (loanAmount / numberOfRate) < (0.3 * monthlyIncome))
end

// Define the rule that uses the queryMatch query
rule "Give system decision"
when
    $request : CarBuyingRequest(user != null, !decisionMade)
    queryMatch($request;)
then
    $request.setAiDecision(1);
    $request.setDecisionMade(true);
    update($request);
end
